### ISSUE TITLE
Select子句，通过as取别名存在BUG

### ISSUE THREAD

**Issue by LegendaryGasai** [IGinX-THU/IGinX#380]
对同一个属性多次as，会进行覆盖。例如下图，对plt_oid属性列，通过as分别取了oid和plt_oid别名，但查询结果中显示的都是plt_oid
![image](https://github.com/IGinX-THU/IGinX/assets/145251974/627e6b72-e8ff-48fd-9ea5-3fc06fb62643)

期望结果：在常规SQL中应该是这样的，对同一列多次as取别名是相互独立的，不会覆盖别名。比如下面的plt_oid as oid,plt_oid as plt_oid，查询结果正常，一个是oid，一个是plt_oid，希望达成这样的效果。
![image](https://github.com/IGinX-THU/IGinX/assets/145251974/a4617ea7-a5fc-40c4-a4d7-e1d6cb971eb7)

**Comment by zhuyuqing** [comment]
我们暂时不支持同一列多次重命名，后续会加上，逐步匹配SQL标准。谢谢
