### ISSUE TITLE
addStorageEngine无法向IGinx中添加数据源

### ISSUE THREAD

**Issue by LegendaryGasai** [IGinX-THU/IGinX#381]
# 版本
<dependency>
    <groupId>cn.edu.tsinghua</groupId>
    <artifactId>iginx-session</artifactId>
    <version>0.5.1</version>
</dependency>

# 描述
通过方法：cn.edu.tsinghua.iginx.session.Session#addStorageEngine
添加数据源API报错，type=null这个问题在其他数据源操作的相关API中也存在，导致无法通过java api添加数据源/查询数据源等相关操作，均会报如图所示的异常。
![image](https://github.com/IGinX-THU/IGinX/assets/145251974/278cd9e0-c728-4522-bc91-a651a3f205a3)

```java
            Session session = iGinxFactory.getSession();
            HashMap<String, String> map = new HashMap<>();
            map.put("engine","postgresql");
            map.put("username","postgres");
            map.put("password","password");
            map.put("has_data","true");
            map.put("data_prefix","dataway");
            map.put("sessionPoolSize","200");
            session.addStorageEngine("xxx.xx.xx.xx", 5432,"relational",map);
            iGinxFactory.closeSession();

```

**Comment by zhuyuqing** [comment]
当前IGinX发布的版本是0.6.0，请使用版本匹配的客户端来连接服务端。

**Comment by csliuyb** [comment]
这个问题是redis升级之后新出现的问题，我们在自己实现过程中已经遇到，iginx在未来连接redis的时候会出现类似问题。

**Comment by zhuyuqing** [comment]
还是使用方法错误的问题，具体使用方法请查阅手册，按手册描述使用，或者联系我组之前对接的同学。
