### ISSUE TITLE
iotdb0.12下载链接失效

### ISSUE THREAD

**Issue by catherine-lisa** [IGinX-THU/IGinX#383]
在
https://github.com/IGinX-THU/IGinX/blob/main/docs/quickStarts/IGinXManual.md
中，提供的iotdb0.12的链接已经失效。
![image](https://github.com/user-attachments/assets/51217f61-a5b3-469f-bac4-6cb0008ee7d2)
原链接：
wget https://mirrors.bfsu.edu.cn/apache/iotdb/0.12.0/apache-iotdb-0.12.0-server-bin.zip

现在该网站已去掉0.12：
![82bd68ed961e7807cf75b5df1c12784](https://github.com/user-attachments/assets/a00a48c6-7a38-4ce5-90c0-6c6c24f096bc)

可以在archive中找到：
wget https://archive.apache.org/dist/iotdb/0.12.0/apache-iotdb-0.12.0-server-bin.zip

**Comment by zhuyuqing** [comment]
IoTDB链接失效问题，可使用以下链接：
https://github.com/IGinX-THU/IGinX-resources/raw/main/resources/apache-iotdb-0.12.6-server-bin.zip
IGinX的使用说明相应更新，谢谢！
