### ISSUE TITLE
(feat) 已经添加的storage engine 无法修改配置信息

### ISSUE THREAD

**Issue by catherine-lisa** [IGinX-THU/IGinX#384]
![image](https://github.com/user-attachments/assets/d3a3acb2-24ec-4ea0-8b39-deb7e4dfc7d2)

对于iginx中已经添加的storage engine 发生了信息的修改（如修改密码），iginx则会连接报错，需要全部清除才能启动

**Comment by zhuyuqing** [comment]
已讨论，已支持，等发新版后，下新版使用
