### ISSUE TITLE
add storage enginee 时，没法识别出has_data前的空格

### ISSUE THREAD

**Issue by catherine-lisa** [IGinX-THU/IGinX#385]

**Comment by catherine-lisa** [comment]
![image](https://github.com/user-attachments/assets/1eed9771-c8f5-43d9-9427-9e20ddd132d3)

ADD STORAGEENGINE ("172.21.11.6", 6664, "iotdb12", "username:root, password:root,  has_data:true, sessionPoolSize:130, schema_prefix:iotschema");
这是我添加iotdb数据库时的语句，但是查询没有数据，看了日志显示如下：

![af97675b7c3955fcfccacb2f5d3b5be](https://github.com/user-attachments/assets/07d6ea0a-fbcf-46a0-bbd5-4ca8ad1269b2)

has_data前的空格没有被识别删除，导致查询没有数据

**Comment by catherine-lisa** [comment]
最新测试，添加数据源时 删除has_data=true前面的两个空格，查询是正常的

![image](https://github.com/user-attachments/assets/04a3580b-dc33-41d5-8b19-3826cb4a1b08)

![image](https://github.com/user-attachments/assets/44628e7c-d570-4112-bad4-76005f052c0e)

**Comment by shinyano** [comment]
![image](https://github.com/user-attachments/assets/de2f118b-1a65-4082-8938-6a580271bede)
在0.6.0发行服务版上未能够复现这个bug

不过建议更新到当前最新发行版0.7.0
