### ISSUE TITLE
as无法对于字段取某些特殊的别名，比如"status"

### ISSUE THREAD

**Issue by LegendaryGasai** [IGinX-THU/IGinX#411]
在blade_visual表中有一名为”**status**“的列，通过**as取为status**别名时报错。
IGinX> select status as status from dataway.blade_visual where 1=1  limit 0,10;
Parse Error: line 2:17 mismatched input 'status' expecting ID
Time cost: 1 ms

表结构如下：
IGinX> select * from dataway.blade_visual where 1=1;
ResultSets:
+---+-----------------------------------+-----------------------------+--------------------------------+--------------------------------+--------------------------------+-----------------------+-------------------------------+-----------------------------+---------------------------+--------------------------+--------------------------------+--------------------------------+
|key|dataway.blade_visual.background_url|dataway.blade_visual.category|dataway.blade_visual.create_dept|dataway.blade_visual.create_time|dataway.blade_visual.create_user|dataway.blade_visual.id|dataway.blade_visual.is_deleted|dataway.blade_visual.password|dataway.blade_visual.status|dataway.blade_visual.title|dataway.blade_visual.update_time|dataway.blade_visual.update_user|
+---+-----------------------------------+-----------------------------+--------------------------------+--------------------------------+--------------------------------+-----------------------+-------------------------------+-----------------------------+---------------------------+--------------------------+--------------------------------+--------------------------------+
+---+-----------------------------------+-----------------------------+--------------------------------+--------------------------------+--------------------------------+-----------------------+-------------------------------+-----------------------------+---------------------------+--------------------------+--------------------------------+--------------------------------+
Empty set.
Time cost: 33 ms

并且无法对任何列通过as取”status“这样的别名，是否是因为**status**是内置的关键字？

**Comment by zhuyuqing** [comment]
status 是关键字。
